name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Esta es la clase 2 del curso de GitHub Actions"
  
  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "Hola 2"
